import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { execSync } from "child_process";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = (process.argv[2] === 'production');

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: ['obsidian','electron','@codemirror/autocomplete','@codemirror/collab',
             '@codemirror/commands','@codemirror/language','@codemirror/lint',
             '@codemirror/search','@codemirror/state','@codemirror/view',
             '@lezer/common','@lezer/highlight','@lezer/lr',...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: false,
  outfile: 'main.js',
});

if (prod) {
  await ctx.rebuild();
  // Use Node.js fs to copy file (cross-platform)
  try {
    fs.copyFileSync('src/styles.css', 'styles.css');
    console.log('✓ styles.css copied from src/');
  } catch(e) {
    console.error('Failed to copy styles.css:', e.message);
  }
  process.exit(0);
} else {
  await ctx.watch();
}
